version: "3.8"
services:
  db:
    image: mysql:5.7
    restart: always
    env_file: ./.env
    ports:
      - 3309:3306
    command: --innodb_use_native_aio=0 --socket=/tmp/mysql.sock --bind_address=0.0.0.0
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: episodios
      MYSQL_ROOT_PASSWORD: episodios
    network_mode: 'podcastzada'
  app:
    restart: "always"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    network_mode: 'podcastzada'
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3003:3000
    environment:
      - CHOKIDAR_USEPOLLING=1